// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAf7BwFyFmswx5DaTmu_sBe5cuNRQ-7ArM',
    appId: '1:163270521083:web:38437c791f6553f471005e',
    messagingSenderId: '163270521083',
    projectId: 'wecare-e525e',
    authDomain: 'wecare-e525e.firebaseapp.com',
    storageBucket: 'wecare-e525e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7MSi5qyMMp2nDVxesTTIESv5WaLqiKhM',
    appId: '1:163270521083:android:0794c960c6169f0971005e',
    messagingSenderId: '163270521083',
    projectId: 'wecare-e525e',
    storageBucket: 'wecare-e525e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-GTHJJtyBZhzxf10TkHxzdMGz9j1mY-s',
    appId: '1:163270521083:ios:ce04ed8b3d8cba3e71005e',
    messagingSenderId: '163270521083',
    projectId: 'wecare-e525e',
    storageBucket: 'wecare-e525e.appspot.com',
    iosClientId: '163270521083-jqee8m971l98q7tgq84v7mng2g05f0ge.apps.googleusercontent.com',
    iosBundleId: 'com.example.wecare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-GTHJJtyBZhzxf10TkHxzdMGz9j1mY-s',
    appId: '1:163270521083:ios:ce04ed8b3d8cba3e71005e',
    messagingSenderId: '163270521083',
    projectId: 'wecare-e525e',
    storageBucket: 'wecare-e525e.appspot.com',
    iosClientId: '163270521083-jqee8m971l98q7tgq84v7mng2g05f0ge.apps.googleusercontent.com',
    iosBundleId: 'com.example.wecare',
  );
}
